#!/usr/bin/python
import os

import shared_values
import git_helper
import os_helper

def filepaths_match(filepath1, filepath2):
    return os.system('diff -q ' + filepath1 + ' ' + filepath2) == 0

def check_current_extras():
    demo_is_sane = True
    robotium_is_sane = True
    for filestem in shared_values.custom_events:
        filename = filestem + '.java'
        extras_filepath = shared_values.EXTRAS_ROOT + filename
        demo_filepath = shared_values.DEMO_ROOT + filename
        robotium_filepath = shared_values.ROBOTIUM_ROOT + filename
        
        if not os.path.exists(extras_filepath) :
            print extras_filepath + ' does not exist. Something is wrong. Exiting.'
            exit(1)

        if os.path.exists(demo_filepath) : 
            print 'checking simpleadsdemo: ' + filestem
            demo_is_sane = filepaths_match(extras_filepath, demo_filepath) and demo_is_sane
        
        if os.path.exists(robotium_filepath) : 
            print 'checking robotium: ' + filestem
            robotium_is_sane = filepaths_match(extras_filepath, robotium_filepath) and robotium_is_sane

    return demo_is_sane and robotium_is_sane

original_branch = git_helper.git_current_branch()
for branch in shared_values.branches_synced_with_master:
    os_helper.try_system_quiet('git co ' + branch)
    if not check_current_extras() :
        print 'Problem in branch: ' + branch + "\n"

os_helper.system_quiet('git co ' + original_branch)
