#!/usr/bin/python
import os

import shared_values
import git_helper
import os_helper

original_branch = git_helper.git_current_branch()
for branch in shared_values.branches_synced_with_master:
    os_helper.try_system('git co ' + branch)
    os_helper.try_system('git pull')

os_helper.system_quiet('git co ' + original_branch)
