#!/usr/bin/python

import os_helper
import git_helper
import shared_values

original_branch = git_helper.git_current_branch()

os_helper.try_system_quiet('git co master')
os_helper.try_system_quiet('git pull')

for branch in shared_values.branches_synced_with_master:
    print branch
    os_helper.try_system('git co ' + branch)
    os_helper.try_system('git merge master --no-edit')

os_helper.system_quiet('git co ' + original_branch)