#!/usr/bin/python
import shutil
import os

import shared_values

if len(os.sys.argv) < 2:
	print 'usage: refresh_extras <filename>'
	exit(1)

filestem = os.sys.argv[1]

filename = filestem + '.java'

def three_arg_usage():
	print 'usage: refresh_extras <filename> <simpleadsdemo|robotium>'
	exit(1)

if filestem in shared_values.duplicated_custom_events:
	# if it's a duplicated custom event, we expect 3 parameters!!
	if len(os.sys.argv) < 3:
		three_arg_usage()

	source_path_type = os.sys.argv[2]
	if source_path_type == 'simpleadsdemo':
	    print 'copying ' + shared_values.DEMO_ROOT + filename + ' to ' + shared_values.ROBOTIUM_ROOT + filename
	    shutil.copyfile(shared_values.DEMO_ROOT + filename, shared_values.ROBOTIUM_ROOT + filename)
	elif source_path_type == 'robotium':
	    print 'copying ' + shared_values.ROBOTIUM_ROOT + filename + ' to ' + shared_values.DEMO_ROOT + filename
	    shutil.copyfile(shared_values.ROBOTIUM_ROOT + filename, shared_values.DEMO_ROOT + filename)
	else:
		three_arg_usage()

	if os.system('git diff --exit-code'):
		print 'comitting in current repo'
		if os.system('git commit -am "updating ' + filename + '"'):
			print 'error: unable to commit in current repo'
			exit(1)
	else:
		print 'no changes in current repo, not committing'

source_path = shared_values.DEMO_ROOT + filename

if filestem in shared_values.custom_events:
	destination_path = shared_values.EXTRAS_ROOT + filename
else:
	print 'error: no matching custom event for filename'
	exit(1)

temp_path = '/tmp/' + filename
shutil.copyfile(source_path, temp_path)
shutil.rmtree('/tmp/mopub_jars', ignore_errors=True)
os.mkdir('/tmp/mopub_jars')
os.system('cp libs/*.jar /tmp/mopub_jars/.')

if os.system('git co master'):
	print 'error: unable to checkout master'
	exit(1)

shutil.copyfile(temp_path, destination_path)
if filestem in shared_values.jars_to_copy:
	os.system('cp /tmp/mopub_jars/* libs/.')

if os.system('git add -A .'):
	print 'error: unable to add files'
	exit(1)

if os.system('git commit -am "updating ' + filename + '"'):
	print 'error: unable to commit in master'
	exit(1)

os.system('script/merge_master_into_everything')
