#!/usr/bin/python
import os

import shared_values
import git_helper
import os_helper

original_branch = git_helper.git_current_branch()
for branch in shared_values.branches_synced_with_master:
    os_helper.try_system_quiet('git co ' + branch)
    if os.system('mvn clean install'):
        print "FALURE!!!!!!!!!!!!!!!"
        exit(1)

os_helper.system_quiet('git co ' + original_branch)

print "SUCCESS!!!!!!!!!!!"